
# SEO settings
title: "Play"
title2: "ground" # default: ""
description: "My place to play with programming."
keywords: "Jekyll, theme, blog, web, playground"
url: https://gangyang2012.github.io # site url
baseurl: null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-89098691-1
repo: https://gangyang2012.github.io
disqus_shortname: "gang"
twitter_username: "GangYang"
comments: true 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Gang Yang"
  job      : "R&D Software Engineer"
  bio      : "All web related skills, Java, C#, Database"
  thumb    : /images/author.jpg
  email    : gang.yang2012@gmail.com
  url      : https://gangyang2012.github.io
  github   : http://github.com/gangyang2012
  twitter  : http://twitter.com/GangY2013
  facebook : https://www.facebook.com/gang.yang2012
  linkedin : https://linkedin.com/in/gang-yang-06453783

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@GangY2013"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
